### ISSUE TITLE
Inventory.json.sha512 format

### ISSUE THREAD

**Issue by tomwrobel** [birkland/ocfl#10]
Hi @birkland!

Thanks for a great piece of code!

I've noticed a small bug: the inventory.json.sha512 is invalid according to the OCFL spec (the filename should be included): https://github.com/tomwrobel/ora_ocfl/issues/22

I hope you don't mind the intrusion! I've been working with the code for a few days now and I'd love the chance to talk further (I realise a petty bug report isn't the best way of doing this, for which I apologise, but I'm trying to document right now).

Best wishes

Tom

**Comment by birkland** [comment]
Hi Tom,

Good catch, thanks!  I'll fix it, and communicate with you via a separate channel
