### ISSUE TITLE
Copy multiple files without copying parent directory

### ISSUE THREAD

**Issue by tomwrobel** [birkland/ocfl#15]
Hi @birkland 

Sorry to be a pain, but there's an odd behaviour that I can't find a way around.

When I do an ocfl cp from a directory, I seem to always copy the parent directory as well, e.g.

For the directory:

```
/parent_directory
   |
   ---- file1
   ---- file2
```

```ocfl cp -r /parent_directory object:id```

gives me a version directory of:

```
v1/content/parent_directory/file1
v2/content/parent_directory/file2
```

Given that parent_directory is likely to be a temporary holding area, I'd rather that it wasn't copied alongside the files. Is there a command that I'm missing here? I'd rather not copy files individually.

With best wishes, and blue skies

Tom

**Comment by birkland** [comment]
Hi Tom,

Sorry for the delay, I have been off the past couple days, and am just checking in on things now

The solution is to use globs:

    ocfl cp -r parent_directory/* foo:bar
 
This will copy everything under `parent_directory` into the object `foo:bar`

**Comment by tomwrobel** [comment]
Thanks!
